insert into hocphan values(null, 'Photoshop')
insert into hocphan values(null, 'Giáo dục quốc phòng - An ninh')
insert into hocphan values(null, 'Cơ sở dữ liệu')
insert into hocphan values(null, 'Hệ quản trị cơ sở dữ liệu')
insert into hocphan values(null, 'Kỹ thuật lập trình')
insert into hocphan values(null, 'Phần cứng và mạng máy tính')
insert into hocphan values(null, 'Chính trị')
insert into hocphan values(null, 'Giáo dục thể chất')
insert into hocphan values(null, 'Phân tích và thiết kế hệ thống')
insert into hocphan values(null, 'Thiết kế Web')
insert into hocphan values(null, 'Lập trình hướng đối tượng')
insert into hocphan values(null, 'Lập trình Windows')
insert into hocphan values(null, 'Cấu trúc dữ liệu & giải thuật')
insert into hocphan values(null, 'Lập trình cơ sở dữ liệu')
insert into hocphan values(null, 'Lập trình Web')
insert into hocphan values(null, 'Đồ án 1')
insert into hocphan values(null, 'Chuyên đề Java')
insert into hocphan values(null, 'XML')
insert into hocphan values(null, 'Pháp luật')
insert into hocphan values(null, 'Công nghệ phần mềm')
insert into hocphan values(null, 'Đồ án 2')
insert into hocphan values(null, 'Lập trình hệ thống nhúng')
insert into hocphan values(null, 'Lập trình trên thiết bị di động')
insert into hocphan values(null, 'Thực tập tốt nghiệp')
insert into hocphan values(null, 'Kiến trúc máy tính')
insert into hocphan values(null, 'Hệ điều hành Windows và Linux')
insert into hocphan values(null, 'Hệ thống số')
insert into hocphan values(null, 'Sửa chữa máy tính')
insert into hocphan values(null, 'Kỹ thuật truyền thông và số liệu')
insert into hocphan values(null, 'Mạng máy tính và quản trị mạng')
insert into hocphan values(null, 'Sửa chữa máy tính nâng cao')
insert into hocphan values(null, 'Xử lý sự cố phần mềm')
insert into hocphan values(null, 'Sửa chữa thiết bị ngoại vi')
insert into hocphan values(null, 'Bảo mật hệ thống thông tin')
insert into hocphan values(null, 'Thiết bị mạng')
insert into hocphan values(null, 'Phần cứng máy tính')
insert into hocphan values(null, 'Xử lý văn bản và bảng tính nâng cao')
insert into hocphan values(null, 'Lập trình quản lý')
insert into hocphan values(null, 'Internet và an toàn dữ liệu')
insert into hocphan values(null, 'Thiết kế đồ họa Corel')
insert into hocphan values(null, 'Lập trình Macro trên Office')
insert into hocphan values(null, 'Lập trình PHP')
insert into hocphan values(null, 'Xử lý ảnh với Photoshop căn bản')
insert into hocphan values(null, 'Thiết kế đồ họa với Corel Draw')
insert into hocphan values(null, 'Quay phim - Chụp ảnh KTS')
insert into hocphan values(null, 'Mỹ thuật cơ bản')
insert into hocphan values(null, 'Thiết kế đồ họa với Illustrator')
insert into hocphan values(null, 'Nguyên lý tạo hình')
insert into hocphan values(null, 'Xử lý âm thanh')
insert into hocphan values(null, 'Thiết kế web căn bản')
insert into hocphan values(null, 'Thiết kế giao diện web với Photoshop')
insert into hocphan values(null, 'Thiết kế đồ họa 2D với Flash')
insert into hocphan values(null, 'Thiết kế đồ họa 3D với 3Dmax')
insert into hocphan values(null, 'Ý tưởng sáng tạo')
insert into hocphan values(null, 'Nghệ thuật chữ')
insert into hocphan values(null, 'Xử lý ảnh với Photoshop nâng cao')
insert into hocphan values(null, 'Thiết kế web nâng cao')
insert into hocphan values(null, 'Công nghệ Multimedia')
insert into hocphan values(null, 'Đồ án thiết kế 3D')
insert into hocphan values(null, 'Chế bản với Indesign')
insert into hocphan values(null, 'Biên tập phim với Premiere')
insert into hocphan values(null, 'Dựng video')
insert into hocphan values(null, 'Lập trình ASP.Net 1')
insert into hocphan values(null, 'Lập Trình PHP 1')
insert into hocphan values(null, 'Lập trình PHP 2')
insert into hocphan values(null, 'Lập trình ASP.Net 2')
insert into hocphan values(null, 'Công nghệ & Dịch vụ Web')

insert into CTNGANH values(2, 1)
insert into CTNGANH values(5, 1)
insert into CTNGANH values(8, 1)
insert into CTNGANH values(1, 2)
insert into CTNGANH values(2, 2)
insert into CTNGANH values(3, 2)
insert into CTNGANH values(4, 2)
insert into CTNGANH values(5, 2)
insert into CTNGANH values(6, 2)
insert into CTNGANH values(7, 2)
insert into CTNGANH values(8, 2)
insert into CTNGANH values(1, 3)
insert into CTNGANH values(2, 3)
insert into CTNGANH values(5, 3)
insert into CTNGANH values(8, 3)
insert into CTNGANH values(2, 4)
insert into CTNGANH values(5, 4)
insert into CTNGANH values(8, 4)
insert into CTNGANH values(2, 5)
insert into CTNGANH values(5, 5)
insert into CTNGANH values(8, 5)
insert into CTNGANH values(2, 6)
insert into CTNGANH values(5, 6)
insert into CTNGANH values(8, 6)
insert into CTNGANH values(2, 7)
insert into CTNGANH values(4, 7)
insert into CTNGANH values(5, 7)
insert into CTNGANH values(8, 7)
insert into CTNGANH values(2, 8)
insert into CTNGANH values(5, 8)
insert into CTNGANH values(8, 8)
insert into CTNGANH values(2, 9)
insert into CTNGANH values(5, 9)
insert into CTNGANH values(8, 9)
insert into CTNGANH values(2, 10)
insert into CTNGANH values(5, 10)
insert into CTNGANH values(8, 10)
insert into CTNGANH values(2, 11)
insert into CTNGANH values(5, 11)
insert into CTNGANH values(8, 11)
insert into CTNGANH values(2, 12)
insert into CTNGANH values(5, 12)
insert into CTNGANH values(8, 12)
insert into CTNGANH values(2, 13)
insert into CTNGANH values(5, 13)
insert into CTNGANH values(8, 13)
insert into CTNGANH values(2, 14)
insert into CTNGANH values(5, 14)
insert into CTNGANH values(8, 14)
insert into CTNGANH values(2, 15)
insert into CTNGANH values(1, 16)
insert into CTNGANH values(2, 16)
insert into CTNGANH values(3, 16)
insert into CTNGANH values(4, 16)
insert into CTNGANH values(5, 16)
insert into CTNGANH values(6, 16)
insert into CTNGANH values(7, 16)
insert into CTNGANH values(8, 16)
insert into CTNGANH values(2, 17)
insert into CTNGANH values(2, 18)
insert into CTNGANH values(8, 18)
insert into CTNGANH values(1, 19)
insert into CTNGANH values(2, 19)
insert into CTNGANH values(3, 19)
insert into CTNGANH values(4, 19)
insert into CTNGANH values(5, 19)
insert into CTNGANH values(6, 19)
insert into CTNGANH values(7, 19)
insert into CTNGANH values(8, 19)
insert into CTNGANH values(2, 20)
insert into CTNGANH values(1, 21)
insert into CTNGANH values(2, 21)
insert into CTNGANH values(3, 21)
insert into CTNGANH values(4, 21)
insert into CTNGANH values(5, 21)
insert into CTNGANH values(6, 21)
insert into CTNGANH values(7, 21)
insert into CTNGANH values(8, 21)
insert into CTNGANH values(2, 22)
insert into CTNGANH values(2, 23)
insert into CTNGANH values(1, 24)
insert into CTNGANH values(2, 24)
insert into CTNGANH values(3, 24)
insert into CTNGANH values(4, 24)
insert into CTNGANH values(5, 24)
insert into CTNGANH values(6, 24)
insert into CTNGANH values(7, 24)
insert into CTNGANH values(8, 24)
insert into CTNGANH values(1, 25)
insert into CTNGANH values(1, 26)
insert into CTNGANH values(1, 27)
insert into CTNGANH values(1, 28)
insert into CTNGANH values(1, 29)
insert into CTNGANH values(1, 30)
insert into CTNGANH values(1, 31)
insert into CTNGANH values(1, 32)
insert into CTNGANH values(1, 33)
insert into CTNGANH values(1, 34)
insert into CTNGANH values(1, 35)
insert into CTNGANH values(1, 36)
insert into CTNGANH values(5, 37)
insert into CTNGANH values(5, 38)
insert into CTNGANH values(5, 39)
insert into CTNGANH values(5, 40)
insert into CTNGANH values(5, 41)
insert into CTNGANH values(5, 42)
insert into CTNGANH values(4, 43)
insert into CTNGANH values(4, 44)
insert into CTNGANH values(4, 45)
insert into CTNGANH values(4, 46)
insert into CTNGANH values(4, 47)
insert into CTNGANH values(4, 48)
insert into CTNGANH values(4, 49)
insert into CTNGANH values(4, 50)
insert into CTNGANH values(4, 51)
insert into CTNGANH values(4, 52)
insert into CTNGANH values(4, 53)
insert into CTNGANH values(4, 54)
insert into CTNGANH values(4, 55)
insert into CTNGANH values(4, 56)
insert into CTNGANH values(4, 57)
insert into CTNGANH values(4, 58)
insert into CTNGANH values(4, 59)
insert into CTNGANH values(4, 60)
insert into CTNGANH values(4, 61)
insert into CTNGANH values(4, 62)
insert into CTNGANH values(8, 63)
insert into CTNGANH values(8, 64)
insert into CTNGANH values(8, 65)
insert into CTNGANH values(8, 66)
insert into CTNGANH values(8, 67)
